---
title: "FireAnimate"
author: "Eric Jensen"
date: "April 28, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(sf)
library(raster)
library(gganimate)
library(mapview)
library(tidyverse)
library(animation) #movie making
library(USAboundaries) # boundary data
library(lubridate)
library(transformr)
library(ggmap)
#library(tmap)
```

Import MTBS data as sf object
```{r}
# Import MTBS polygon data
mtbs <- st_read('C:/Users/erjensen/Documents/Thesis/ThesisGIS/MTBSpolys/mtbs_perims_DD.shp') %>%
  st_transform(crs = 4326) 
mtbs$StartDate <- as.Date(with(mtbs, paste(Year, StartMonth, StartDay,sep="-")), "%Y-%m-%d")

# Import counts of MTBS polygons
mtbs_counts <- st_read('C:/Users/erjensen/Documents/Thesis/ThesisGIS/MTBSpolys/MBTSpolys_counts.shp') %>%
  st_transform(crs = 4326) 

# Import Great Basin boundary for plotting and subsetting
gb_bounds <- st_read('C:/Users/erjensen/Documents/Thesis/ThesisGIS/LIIIGBBoundary/LIIIGBBoundary.shp') %>%
  st_transform(crs = 4326)

# Spatially subset data to the Great Basin
gb_mtbs <- mtbs[gb_bounds,] %>%
  dplyr::mutate(SizeClass=cut(Acres, breaks=c(-Inf, 5000, 50000, 150000, Inf), labels=c("Small","Medium","Large","Very large")))
```

Animate a map
```{r}
options(scipen=999)
# Get ggmap basemap
myMap <- get_googlemap(c(x = -115.5, y = 41),
          maptype = "hybrid", 
          crop = FALSE,
          zoom = 6,
          size = c(1000, 1000))
ggmap(myMap)

# Create static map of fire counts for finishing gif
ggmap(myMap)+
  geom_sf(gb_bounds, mapping = aes(), color = 'black', fill = NA, inherit.aes = FALSE, cex = 1.5) +
  geom_sf(mtbs_counts, mapping = aes(fill = COUNT_), alpha = .9, color = NA, inherit.aes = FALSE) +
  scale_fill_gradient(low = '#EEDB1F', high = "#CA0000") +
  labs(title = "Times burned (1984—2017)", fill = 'Times\nburned', x = "", y = "") +
  xlim(-121.5,-110.5) + ylim(36,44) +
  theme_minimal() +
  theme(legend.position = c(0.92, 0.2), legend.background = element_rect(fill = alpha('white',.8)))

# Create map to animate by year
map <- ggmap(myMap)+
  geom_sf(gb_bounds, mapping = aes(), color = 'black', fill = NA, inherit.aes = FALSE, cex = 1.5) +
  geom_sf(gb_mtbs, mapping = aes(fill = SizeClass), color = NA, inherit.aes = FALSE, alpha = .9) +
  scale_fill_manual(values=c("#E8E104", "#FFA811", "#FF6B11", "#FF0000")) +
  labs(title = "Great Basin Fires (1984-2017)", fill = 'Size class', x = "", y = "") +
  xlim(-121.5,-110.5) + ylim(36,44) +
  theme_minimal() +
  theme(legend.position = c(0.88, 0.15), legend.background = element_rect(fill = alpha('white',.8)))

# Apply animation to annual map
ani_map <- map + transition_time(Year) +
  labs(title = "Great Basin Fires (1984-2017)             Year: {frame_time}") +
  shadow_mark(alpha = .4) 

anim <- animate(ani_map)

magick::image_write(anim, path='C:/Users/erjensen/Documents/Thesis/gb_fire_animation.gif')

```

Animate a histogram
```{r}
# Prep data for plotting yearly acres against year // color by size of fire
gb_mtbs_yrly <- gb_mtbs %>%
  dplyr::group_by(Year, SizeClass) %>%
  dplyr::mutate(YrAcres = sum(Acres)) %>%
  dplyr::select(Year, SizeClass, YrAcres) %>%
  st_drop_geometry() %>%
  unique()

# Plot bar chart for acres burned by year, colored by fire size
ani_bar <- ggplot()+ 
  geom_bar(gb_mtbs_yrly, mapping = aes(x = Year, y = YrAcres, fill = SizeClass), stat = "identity") +
  scale_fill_manual(values=c("#E8E104", "#FFA811", "#FF6B11", "#FF0000")) +
  scale_x_continuous(breaks=seq(1984, 2018, 2)) +
  labs(title = "Great Basin fire sizes by year (1984-2017)", x = "", y = "Acres burned", fill = 'Fire size')  +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45)) +
  transition_time(Year) +
  shadow_mark(alpha = .4)

anim <- animate(ani_bar)

magick::image_write(anim, path='C:/Users/erjensen/Documents/Thesis/gb_fire_bar_animation.gif')

# # Prep data for plotting number of fires by size
# gb_mtbs_hist <- gb_mtbs %>%
#   mutate(AcreClass=cut(Acres, breaks=seq(0,600000,10000), labels=seq(5000,595000,10000))) %>%
#   mutate(AcreClass = as.numeric(as.character(AcreClass))) %>%
#   group_by(AcreClass, Year) %>%
#   tally() 
# 
# #plotting number of fires by size
# ggplot()+ 
#   geom_bar(gb_mtbs_hist, mapping = aes(x = AcreClass, y = n, fill = as.factor(Year)), stat = "identity") +
#   scale_y_sqrt() +
#   theme(axis.text.x = element_text(angle = 90))
```

